version: "3.9"

services:
  # webapp:
  #   build:
  #     context: ./webapp
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - "5000:80"
  #   volumes:
  #     - ./webapp:/usr/src/app
  #     - /usr/src/app/node_modules
  # api:
  #   build:
  #     context: ./webapp/api
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - "4000:4000"
  nginx:
    image: nginx:stable
    restart: unless-stopped
    ports:
      - "8764:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data:/home/static
